#!/usr/bin/env th
local hue = require './hue'

local syntax = {
   {
      name = 'Jade Tag Name',
      exemple = [[meta head]],
      selector = 'entity.name.tag.jade',
      color = hue.violet,
      back = hue.base,
      style = 'bold italic',
   },
   {
      name = 'tag',
      exemple = [[ div i p a]],
      back = hue.violet01,
      color = hue.violet,
      style = 'bold',
      selector = 'entity.name.tag.jade ',
   },
   {
      name = 'id',
      exemple = [[ is]],
      back = hue.pink01,
      color = hue.pink,
      style = 'bold italic',
      selector = 'constant',
   },
   {
      name= 'class',
      exemple= [[ class]],
      color= hue.green,
      back= hue.green01,
      style= 'bold italic',
      selector= 'constant.language ',
   },
   {
      name= 'attribute',
      exemple= [[opt]],
      color= hue.base02,
      style= '',
      selector= 'entity.other.attribute-name.pseudo-element, entity.other ',
   },
   {
      name= 'support',
      exemple= [['.click']],
      back= hue.cyan01,
      color= hue.cyan,
      style= '',
      selector= 'support.function ',
   },{
      name= 'punctuation',
      exemple= [[() , ]],
      back= hue.base,
      color= hue.black,
      style= 'bold',
      selector= 'punctuation ',
   },
   {
      name= 'text',
      selector= 'text ',
      exemple= [[ text]],
      back= hue.black01,
      color= hue.black,
      style= 'style',
   },
   {
      name = 'string',
      selector = 'string ',
      exemple = [[string]],
      color = hue.violet,
      back = hue.violet01,
      style = 'italic',
   },
   {
      name = 'preprocess',
      selector = 'string.interpolated ',
      exemple = [[ #{}]],
      back = hue.blue01,
      color = hue.blue,
      style = '',
   },
   {
      name = 'comment',
      selector = 'comment ',
      exemple = [[comment]],
      back = hue.base,
      color = hue.black,
      style = 'bold',
   },
   {
      name = 'keyword',
      selector = 'keyword ',
      exemple = [[ $ js]],
      back = hue.black01,
      color = hue.black,
      style = 'bold',
   },
   {
      name = 'operator',
      selector = 'keyword.operator ',
      exemple = [[ 'in']],
      back = hue.orange01,
      color = hue.orange,
      style = 'bold',
   },
   {
      name = 'storage',
      selector = 'storage ',
      exemple = [[ functions]],
      back = hue.orange01,
      color = hue.orange,
      style = 'bold',
   },
   {
      name = 'Jade Doctype',
      selector = 'keyword.other.doctype.jade',
      back = hue.cyan01,
      color = hue.cyan,
      style = '',
   },
   {
      name = 'Jade Script Tag Name',
      selector = 'entity.name.tag.script.jade',
      back = hue.red01,
      color = hue.red,
      style = '',
   },

   {
      name = 'Jade Attribute',
      selector = 'meta.tag.attribute.jade',
      back = hue.orange01,
      color = hue.orange,
      style = '',
   },

   {
      name = 'Jade Attribute Name',
      selector = 'entity.other.attribute-name.jade',
      back = hue.orange01,
      color = hue.orange,
      style = '',
   },

   {
      name = 'Jade Attribute Value',
      selector = 'string.quoted.double.jade',
      back = hue.blue01,
      color = hue.blue,
      style = '',
   },

   -- {
   --    name = 'Jade Id',
   --    selector = 'meta.tag.attribute.id.jade',
   --    back = hue.pink01,
   --    color = hue.pink,
   --    style = '',
   -- },
   -- {
   --    name = 'Jade Class',
   --    selector = 'meta.tag.attribute.class.jade',
   --    back = hue.green01,
   --    color = hue.green,
   --    style = 'bold',
   -- }
}
return syntax
